services:
  app:
    image: house-price:prod
    container_name: house-price-prod
    ports: ["8501:8501"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8501/"]
      interval: 30s
      timeout: 5s
      retries: 3
